# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f145f29c58af31ff231aa3373b77961c33c4290af0ed72e75ed57a3c3ebb2ee556aeff3a01847b5b2865390af2c629141ff75941643a8c17916b73456f29c1dc

test:
  secret_key_base: 346bc8d299d9462b007ec8194e42607285cd032cd5fbb7b8eeb63757536b29e88c12ee6e33673e798502678128909dc39b46977351ef7332035d82f40100fec8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
